from typing import Protocol

from vinculante.domain.entities import Match, Proposal, Section, TargetDocument


class ProposalRepositoryProtocol(Protocol):
    def get_by_id(self, id: int) -> Proposal | None: ...
    def get_all(self) -> list[Proposal]: ...
    def get_by_source_file(self, source_file: str) -> list[Proposal]: ...
    def get_by_target(self, target_id: int) -> list[Proposal]: ...
    def save(self, proposal: Proposal) -> Proposal: ...
    def bulk_save(self, proposals: list[Proposal]) -> list[Proposal]: ...
    def delete(self, id: int) -> None: ...


class TargetRepositoryProtocol(Protocol):
    def get_by_id(self, id: int) -> TargetDocument | None: ...
    def get_all(self) -> list[TargetDocument]: ...
    def save(self, target: TargetDocument) -> TargetDocument: ...
    def delete(self, id: int) -> None: ...


class SectionRepositoryProtocol(Protocol):
    def get_by_id(self, id: int) -> Section | None: ...
    def get_by_target(self, target_id: int) -> list[Section]: ...
    def count_matchable_by_target(self, target_id: int) -> int: ...
    def save(self, section: Section) -> Section: ...
    def bulk_save(self, sections: list[Section]) -> list[Section]: ...
    def find_similar(self, embedding: list[float], target_id: int, k: int) -> list[Section]: ...
    def delete(self, id: int) -> None: ...


class MatchRepositoryProtocol(Protocol):
    def get_by_id(self, id: int) -> Match | None: ...
    def get_all(self) -> list[Match]: ...
    def get_by_proposal(self, proposal_id: int) -> list[Match]: ...
    def get_by_status(self, status: str) -> list[Match]: ...
    def save(self, match: Match) -> Match: ...
    def bulk_save(self, matches: list[Match]) -> list[Match]: ...
    def delete(self, id: int) -> None: ...
