"""proposal_target_id

Revision ID: 091e4fb15314
Revises: ef8b8cf37ec5
Create Date: 2026-04-21 13:47:17.871160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '091e4fb15314'
down_revision: Union[str, Sequence[str], None] = 'ef8b8cf37ec5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposals', sa.Column('target_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'proposals', 'target_documents', ['target_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'proposals', type_='foreignkey')
    op.drop_column('proposals', 'target_id')
    # ### end Alembic commands ###
