"""section_is_matchable

Revision ID: bcb2c90c5497
Revises: 067ecae576f1
Create Date: 2026-04-29 06:46:11.642798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcb2c90c5497'
down_revision: Union[str, Sequence[str], None] = '067ecae576f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sections', sa.Column('is_matchable', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sections', 'is_matchable')
    # ### end Alembic commands ###
