"""proposal embedding

Revision ID: ef8b8cf37ec5
Revises: fd9abedf0c7d
Create Date: 2026-04-21 09:35:22.457856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'ef8b8cf37ec5'
down_revision: Union[str, Sequence[str], None] = 'fd9abedf0c7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposals', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposals', 'embedding')
    # ### end Alembic commands ###
